name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd frontend # ถ้า `package.json` อยู่ในโฟลเดอร์ `frontend`
        npm ci

    - name: Build
      run: |
        cd frontend # ถ้า `package.json` อยู่ในโฟลเดอร์ `frontend`
        npm run build

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RR2RUN }}
        channel-id: live
        projectId: rr2run
